server:
  tomcat:
    uri-encoding: utf-8
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true
  output:
    ansi:
      enabled: always
  devtools:
    livereload:
      enabled: true
  data:
    web:
      pageable:
        one-indexed-parameters: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    urls-primary-name: 동네서점 API
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

#  http://localhost:8080/swagger-ui/index.html
#  http://localhost:8080/h2-consol
